name: Upload full source to release

on:
  status

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Clone.
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install prerequisites.
      run: |
        pip install git-archive-all

        p=$(echo frk-v${GITHUB_REF##*/v}-full.tar.gz)
        echo "TAG=$p" >> $GITHUB_ENV
    - name: Build assets.
      run: |
        mkdir -p dist/
        echo "$TAG"
        ~/.local/bin/git-archive-all ./dist/${TAG}
